# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addParams_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddParamsPage(object):
    def setupUi(self, AddParamsPage):
        AddParamsPage.setObjectName("AddParamsPage")
        AddParamsPage.resize(400, 300)
        self.btn_saveParam = QtWidgets.QPushButton(AddParamsPage)
        self.btn_saveParam.setGeometry(QtCore.QRect(90, 190, 81, 31))
        self.btn_saveParam.setObjectName("btn_saveParam")
        self.btn_cancelParam = QtWidgets.QPushButton(AddParamsPage)
        self.btn_cancelParam.setGeometry(QtCore.QRect(220, 190, 81, 31))
        self.btn_cancelParam.setObjectName("btn_cancelParam")
        self.le_config_key = QtWidgets.QLineEdit(AddParamsPage)
        self.le_config_key.setGeometry(QtCore.QRect(200, 40, 131, 31))
        self.le_config_key.setObjectName("le_config_key")
        self.label = QtWidgets.QLabel(AddParamsPage)
        self.label.setGeometry(QtCore.QRect(90, 50, 54, 12))
        self.label.setObjectName("label")
        self.le_config_value = QtWidgets.QLineEdit(AddParamsPage)
        self.le_config_value.setGeometry(QtCore.QRect(200, 100, 131, 31))
        self.le_config_value.setObjectName("le_config_value")
        self.label_2 = QtWidgets.QLabel(AddParamsPage)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 54, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(AddParamsPage)
        QtCore.QMetaObject.connectSlotsByName(AddParamsPage)

    def retranslateUi(self, AddParamsPage):
        _translate = QtCore.QCoreApplication.translate
        AddParamsPage.setWindowTitle(_translate("AddParamsPage", "服务配置"))
        self.btn_saveParam.setText(_translate("AddParamsPage", "保存"))
        self.btn_cancelParam.setText(_translate("AddParamsPage", "取消"))
        self.label.setText(_translate("AddParamsPage", "参数名"))
        self.label_2.setText(_translate("AddParamsPage", "参数值"))
