# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addServer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddServerPage(object):
    def setupUi(self, AddServerPage):
        AddServerPage.setObjectName("AddServerPage")
        AddServerPage.resize(451, 397)
        self.le_newServerName = QtWidgets.QLineEdit(AddServerPage)
        self.le_newServerName.setGeometry(QtCore.QRect(200, 60, 141, 31))
        self.le_newServerName.setObjectName("le_newServerName")
        self.labe_ip_3 = QtWidgets.QLabel(AddServerPage)
        self.labe_ip_3.setGeometry(QtCore.QRect(110, 70, 51, 16))
        self.labe_ip_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labe_ip_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labe_ip_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labe_ip_3.setObjectName("labe_ip_3")
        self.btn_saveServer = QtWidgets.QPushButton(AddServerPage)
        self.btn_saveServer.setGeometry(QtCore.QRect(110, 320, 81, 31))
        self.btn_saveServer.setObjectName("btn_saveServer")
        self.btn_closeServer = QtWidgets.QPushButton(AddServerPage)
        self.btn_closeServer.setGeometry(QtCore.QRect(260, 320, 81, 31))
        self.btn_closeServer.setObjectName("btn_closeServer")
        self.label_3 = QtWidgets.QLabel(AddServerPage)
        self.label_3.setGeometry(QtCore.QRect(110, 120, 54, 12))
        self.label_3.setObjectName("label_3")
        self.le_new_ip = QtWidgets.QLineEdit(AddServerPage)
        self.le_new_ip.setGeometry(QtCore.QRect(200, 110, 141, 31))
        self.le_new_ip.setObjectName("le_new_ip")
        self.label_4 = QtWidgets.QLabel(AddServerPage)
        self.label_4.setGeometry(QtCore.QRect(110, 170, 54, 12))
        self.label_4.setObjectName("label_4")
        self.le_new_port = QtWidgets.QLineEdit(AddServerPage)
        self.le_new_port.setGeometry(QtCore.QRect(200, 160, 141, 31))
        self.le_new_port.setObjectName("le_new_port")
        self.label_5 = QtWidgets.QLabel(AddServerPage)
        self.label_5.setGeometry(QtCore.QRect(110, 220, 54, 12))
        self.label_5.setObjectName("label_5")
        self.le_new_user = QtWidgets.QLineEdit(AddServerPage)
        self.le_new_user.setGeometry(QtCore.QRect(200, 210, 141, 31))
        self.le_new_user.setObjectName("le_new_user")
        self.label_6 = QtWidgets.QLabel(AddServerPage)
        self.label_6.setGeometry(QtCore.QRect(110, 270, 54, 12))
        self.label_6.setObjectName("label_6")
        self.le_new_passwd = QtWidgets.QLineEdit(AddServerPage)
        self.le_new_passwd.setGeometry(QtCore.QRect(200, 260, 141, 31))
        self.le_new_passwd.setObjectName("le_new_passwd")

        self.retranslateUi(AddServerPage)
        QtCore.QMetaObject.connectSlotsByName(AddServerPage)

    def retranslateUi(self, AddServerPage):
        _translate = QtCore.QCoreApplication.translate
        AddServerPage.setWindowTitle(_translate("AddServerPage", "新增环境"))
        self.labe_ip_3.setText(_translate("AddServerPage", "环境名"))
        self.btn_saveServer.setText(_translate("AddServerPage", "保存"))
        self.btn_closeServer.setText(_translate("AddServerPage", "取消"))
        self.label_3.setText(_translate("AddServerPage", "IP"))
        self.label_4.setText(_translate("AddServerPage", "port"))
        self.label_5.setText(_translate("AddServerPage", "用户"))
        self.label_6.setText(_translate("AddServerPage", "密码"))
