# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverConfig_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerConfigPage(object):
    def setupUi(self, ServerConfigPage):
        ServerConfigPage.setObjectName("ServerConfigPage")
        ServerConfigPage.resize(677, 489)
        self.btn_addParam = QtWidgets.QPushButton(ServerConfigPage)
        self.btn_addParam.setGeometry(QtCore.QRect(130, 210, 81, 31))
        self.btn_addParam.setObjectName("btn_addParam")
        self.btn_delParam = QtWidgets.QPushButton(ServerConfigPage)
        self.btn_delParam.setGeometry(QtCore.QRect(400, 210, 81, 31))
        self.btn_delParam.setObjectName("btn_delParam")
        self.tw_serverConfig = QtWidgets.QTableWidget(ServerConfigPage)
        self.tw_serverConfig.setGeometry(QtCore.QRect(100, 280, 441, 181))
        self.tw_serverConfig.setObjectName("tw_serverConfig")
        self.tw_serverConfig.setColumnCount(0)
        self.tw_serverConfig.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(ServerConfigPage)
        self.label_3.setGeometry(QtCore.QRect(80, 60, 54, 12))
        self.label_3.setObjectName("label_3")
        self.le_config_ip = QtWidgets.QLineEdit(ServerConfigPage)
        self.le_config_ip.setGeometry(QtCore.QRect(130, 50, 131, 31))
        self.le_config_ip.setObjectName("le_config_ip")
        self.label_4 = QtWidgets.QLabel(ServerConfigPage)
        self.label_4.setGeometry(QtCore.QRect(340, 60, 54, 12))
        self.label_4.setObjectName("label_4")
        self.le_config_port = QtWidgets.QLineEdit(ServerConfigPage)
        self.le_config_port.setGeometry(QtCore.QRect(400, 50, 131, 31))
        self.le_config_port.setObjectName("le_config_port")
        self.label_5 = QtWidgets.QLabel(ServerConfigPage)
        self.label_5.setGeometry(QtCore.QRect(80, 110, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(ServerConfigPage)
        self.label_6.setGeometry(QtCore.QRect(340, 110, 54, 12))
        self.label_6.setObjectName("label_6")
        self.le_config_user = QtWidgets.QLineEdit(ServerConfigPage)
        self.le_config_user.setGeometry(QtCore.QRect(130, 100, 131, 31))
        self.le_config_user.setObjectName("le_config_user")
        self.le_config_passwd = QtWidgets.QLineEdit(ServerConfigPage)
        self.le_config_passwd.setGeometry(QtCore.QRect(400, 100, 131, 31))
        self.le_config_passwd.setObjectName("le_config_passwd")
        self.btn_updateParam = QtWidgets.QPushButton(ServerConfigPage)
        self.btn_updateParam.setGeometry(QtCore.QRect(260, 210, 81, 31))
        self.btn_updateParam.setObjectName("btn_updateParam")

        self.retranslateUi(ServerConfigPage)
        QtCore.QMetaObject.connectSlotsByName(ServerConfigPage)

    def retranslateUi(self, ServerConfigPage):
        _translate = QtCore.QCoreApplication.translate
        ServerConfigPage.setWindowTitle(_translate("ServerConfigPage", "环境配置"))
        self.btn_addParam.setText(_translate("ServerConfigPage", "添加"))
        self.btn_delParam.setText(_translate("ServerConfigPage", "删除"))
        self.label_3.setText(_translate("ServerConfigPage", "IP"))
        self.label_4.setText(_translate("ServerConfigPage", "port"))
        self.label_5.setText(_translate("ServerConfigPage", "用户"))
        self.label_6.setText(_translate("ServerConfigPage", "密码"))
        self.btn_updateParam.setText(_translate("ServerConfigPage", "修改"))
